version: "3.8"
services:
  get-magnet:
    image: ghcr.io/nekoimi/get-magnet:latest
    container_name: get-magnet
    hostname: get-magnet
    networks:
      - get_magnet
    privileged: true
    restart: on-failure
    environment:
      TZ: Asia/Shanghai
      LOG_LEVEL: debug
      DB_DSN:
      ARIA2_JSONRPC:
      ARIA2_SECRET:
      HTTP_PROXY: socks5://127.0.0.1:2080
      HTTPS_PROXY: socks5://127.0.0.1:2080
    volumes:
      - type: bind
        source: ""
        target: "/var/lib/rod-data"
networks:
  get_magnet:
    driver: bridge
