// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: fetch.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_fetch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Html          string                 `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_fetch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FetchResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *FetchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_fetch_proto protoreflect.FileDescriptor

const file_fetch_proto_rawDesc = "" +
	"\n" +
	"\vfetch.proto\x12\x04grpc\":\n" +
	"\fFetchRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"S\n" +
	"\rFetchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04html\x18\x02 \x01(\tR\x04html\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xb6\x01\n" +
	"\x10PageFetchService\x120\n" +
	"\x05Fetch\x12\x12.grpc.FetchRequest\x1a\x13.grpc.FetchResponse\x125\n" +
	"\n" +
	"FetchJavDB\x12\x12.grpc.FetchRequest\x1a\x13.grpc.FetchResponse\x129\n" +
	"\x0eFetchSehuatang\x12\x12.grpc.FetchRequest\x1a\x13.grpc.FetchResponseB!Z\x1finternal/drission_rod/grpc;grpcb\x06proto3"

var (
	file_fetch_proto_rawDescOnce sync.Once
	file_fetch_proto_rawDescData []byte
)

func file_fetch_proto_rawDescGZIP() []byte {
	file_fetch_proto_rawDescOnce.Do(func() {
		file_fetch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fetch_proto_rawDesc), len(file_fetch_proto_rawDesc)))
	})
	return file_fetch_proto_rawDescData
}

var file_fetch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fetch_proto_goTypes = []any{
	(*FetchRequest)(nil),  // 0: grpc.FetchRequest
	(*FetchResponse)(nil), // 1: grpc.FetchResponse
}
var file_fetch_proto_depIdxs = []int32{
	0, // 0: grpc.PageFetchService.Fetch:input_type -> grpc.FetchRequest
	0, // 1: grpc.PageFetchService.FetchJavDB:input_type -> grpc.FetchRequest
	0, // 2: grpc.PageFetchService.FetchSehuatang:input_type -> grpc.FetchRequest
	1, // 3: grpc.PageFetchService.Fetch:output_type -> grpc.FetchResponse
	1, // 4: grpc.PageFetchService.FetchJavDB:output_type -> grpc.FetchResponse
	1, // 5: grpc.PageFetchService.FetchSehuatang:output_type -> grpc.FetchResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fetch_proto_init() }
func file_fetch_proto_init() {
	if File_fetch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fetch_proto_rawDesc), len(file_fetch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fetch_proto_goTypes,
		DependencyIndexes: file_fetch_proto_depIdxs,
		MessageInfos:      file_fetch_proto_msgTypes,
	}.Build()
	File_fetch_proto = out.File
	file_fetch_proto_goTypes = nil
	file_fetch_proto_depIdxs = nil
}
