// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: fetch.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PageFetchService_Fetch_FullMethodName          = "/grpc.PageFetchService/Fetch"
	PageFetchService_FetchJavDB_FullMethodName     = "/grpc.PageFetchService/FetchJavDB"
	PageFetchService_FetchSehuatang_FullMethodName = "/grpc.PageFetchService/FetchSehuatang"
)

// PageFetchServiceClient is the client API for PageFetchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PageFetchServiceClient interface {
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	FetchJavDB(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
	FetchSehuatang(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error)
}

type pageFetchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPageFetchServiceClient(cc grpc.ClientConnInterface) PageFetchServiceClient {
	return &pageFetchServiceClient{cc}
}

func (c *pageFetchServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, PageFetchService_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageFetchServiceClient) FetchJavDB(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, PageFetchService_FetchJavDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pageFetchServiceClient) FetchSehuatang(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchResponse)
	err := c.cc.Invoke(ctx, PageFetchService_FetchSehuatang_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PageFetchServiceServer is the server API for PageFetchService service.
// All implementations must embed UnimplementedPageFetchServiceServer
// for forward compatibility.
type PageFetchServiceServer interface {
	Fetch(context.Context, *FetchRequest) (*FetchResponse, error)
	FetchJavDB(context.Context, *FetchRequest) (*FetchResponse, error)
	FetchSehuatang(context.Context, *FetchRequest) (*FetchResponse, error)
	mustEmbedUnimplementedPageFetchServiceServer()
}

// UnimplementedPageFetchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPageFetchServiceServer struct{}

func (UnimplementedPageFetchServiceServer) Fetch(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedPageFetchServiceServer) FetchJavDB(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchJavDB not implemented")
}
func (UnimplementedPageFetchServiceServer) FetchSehuatang(context.Context, *FetchRequest) (*FetchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchSehuatang not implemented")
}
func (UnimplementedPageFetchServiceServer) mustEmbedUnimplementedPageFetchServiceServer() {}
func (UnimplementedPageFetchServiceServer) testEmbeddedByValue()                          {}

// UnsafePageFetchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PageFetchServiceServer will
// result in compilation errors.
type UnsafePageFetchServiceServer interface {
	mustEmbedUnimplementedPageFetchServiceServer()
}

func RegisterPageFetchServiceServer(s grpc.ServiceRegistrar, srv PageFetchServiceServer) {
	// If the following call pancis, it indicates UnimplementedPageFetchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PageFetchService_ServiceDesc, srv)
}

func _PageFetchService_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageFetchServiceServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageFetchService_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageFetchServiceServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageFetchService_FetchJavDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageFetchServiceServer).FetchJavDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageFetchService_FetchJavDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageFetchServiceServer).FetchJavDB(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PageFetchService_FetchSehuatang_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PageFetchServiceServer).FetchSehuatang(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PageFetchService_FetchSehuatang_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PageFetchServiceServer).FetchSehuatang(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PageFetchService_ServiceDesc is the grpc.ServiceDesc for PageFetchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PageFetchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.PageFetchService",
	HandlerType: (*PageFetchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _PageFetchService_Fetch_Handler,
		},
		{
			MethodName: "FetchJavDB",
			Handler:    _PageFetchService_FetchJavDB_Handler,
		},
		{
			MethodName: "FetchSehuatang",
			Handler:    _PageFetchService_FetchSehuatang_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fetch.proto",
}
