<template>
 <div class="v21-stack">
  <header class="v21-header"><div><div class="v21-eyebrow">Workspace / 数据</div><h1>数据集与记录</h1><p>按目标数据查询结果，并追溯每条记录的来源、运行和原文。</p></div><el-button type="primary" :disabled="!projectId" @click="dialog=true">新建数据集</el-button></header>
  <p v-if="error" class="v21-error" role="alert">{{error}}</p>
  <div class="v21-grid two"><section class="v21-card"><h2>数据集</h2><div v-if="loading" class="v21-empty">加载中…</div><div v-else-if="!datasets.length" class="v21-empty">当前项目还没有数据集。创建后即可为采集器定义目标字段。</div><button v-for="item in datasets" :key="item.id" class="dataset-item" :class="{active:item.id===selected}" @click="choose(item.id)"><span><strong>{{item.name}}</strong><small>{{item.record_type}} · Schema v{{item.schema_version}}</small></span><span>→</span></button></section><section class="v21-card"><h2>{{current?.name||'字段结构'}}</h2><div v-if="!current" class="v21-empty">选择一个数据集查看字段结构。</div><template v-else><div class="v21-note">唯一键：{{keyNames.join(' + ')||'未定义'}} · 空值策略：{{current.empty_value_policy==='preserve'?'保留已有值':'允许覆盖'}}</div><div v-for="field in fields" :key="field.field_key" class="v21-row"><div><strong>{{field.label}}</strong><small>{{field.field_key}} · {{field.field_type}}{{field.multiple?'[]':''}}</small></div><span v-if="field.required" class="v21-status">必填</span></div></template></section></div>
  <section class="v21-card"><div class="records-head"><div><h2>记录 {{total ? `· ${total}` : ''}}</h2><span class="v21-muted">{{current?.name||'请选择数据集'}}</span></div><el-input v-model="query" placeholder="按唯一键或字段筛选当前页" clearable style="max-width:280px" /></div><div v-if="!selected" class="v21-empty">选择数据集后查看采集结果。</div><div v-else-if="!filtered.length" class="v21-empty">暂无匹配记录。发布采集器并正式运行后，记录会出现在这里。</div><div v-else class="v21-table-wrap"><table class="v21-table"><thead><tr><th>唯一键</th><th>字段摘要</th><th>最近发现</th><th>操作</th></tr></thead><tbody><tr v-for="row in filtered" :key="row.id"><td>{{row.canonical_key}}</td><td>{{summary(row)}}</td><td>{{formatDate(row.last_seen_at)}}</td><td><button class="v21-link text-button" @click="openRecord(row.id)">字段与来源 →</button></td></tr></tbody></table></div><div class="pager"><el-button :disabled="page<=1" @click="page--;loadRecords()">上一页</el-button><span>第 {{page}} 页</span><el-button :disabled="page*20>=total" @click="page++;loadRecords()">下一页</el-button></div></section>
  <el-drawer v-model="recordDrawer" size="min(620px,96vw)" title="记录与来源"><div v-if="detail"><h2>{{detail.record.canonical_key}}</h2><p class="v21-muted">首次发现 {{formatDate(detail.record.first_seen_at)}} · 最近发现 {{formatDate(detail.record.last_seen_at)}}</p><h3>当前字段</h3><dl class="facts"><template v-for="(value,key) in jsonValue(detail.record.normalized)" :key="key"><dt>{{key}}</dt><dd>{{display(value)}}</dd></template></dl><h3>来源证据</h3><div v-if="!detail.observations?.length" class="v21-empty">暂无来源观察。</div><div v-for="ob in detail.observations" :key="ob.id" class="v21-row"><div><strong>{{ob.decision}} · {{formatDate(ob.observed_at)}}</strong><small>采集器 #{{ob.workflow_id||'—'}} · 版本 #{{ob.workflow_version_id||'—'}} · Schema v{{ob.schema_version}}</small><a v-if="ob.source_url" :href="ob.source_url" target="_blank" rel="noopener noreferrer" class="v21-link">来源页面 ↗</a></div><div><router-link v-if="ob.run_id" class="v21-link" :to="{path:'/workspace/runs',query:{id:String(ob.run_id)}}">查看运行</router-link><br><button v-if="ob.document_id" class="v21-link text-button" @click="showDocument(ob.document_id)">原始文档</button></div></div><h3>字段修订</h3><div v-for="rev in detail.revisions" :key="rev.id" class="v21-row"><span>{{formatDate(rev.created_at)}}</span><span>{{display(jsonValue(rev.changed_fields))}}</span></div></div></el-drawer>
  <el-dialog v-model="documentDialog" title="原始文档" width="min(900px,96vw)"><pre class="document-content">{{documentContent}}</pre></el-dialog>
  <el-dialog v-model="dialog" title="新建数据集" width="min(780px,96vw)"><div class="form-pair"><div class="v21-field"><label for="dataset-name">数据集名称</label><input id="dataset-name" v-model="form.name" placeholder="例如：文章" /></div><div class="v21-field"><label for="dataset-code">标识</label><input id="dataset-code" v-model="form.code" placeholder="例如：article" /></div><div class="v21-field"><label for="dataset-type">记录类型</label><input id="dataset-type" v-model="form.record_type" placeholder="例如：article" /></div><div class="v21-field"><label for="empty-policy">空值更新</label><select id="empty-policy" v-model="form.empty_value_policy"><option value="preserve">保留已有非空值</option><option value="overwrite">允许空值覆盖</option></select></div></div><div class="fields-title"><strong>字段结构</strong><el-button size="small" @click="addField">添加字段</el-button></div><div v-for="(field,index) in form.fields" :key="index" class="field-editor"><input v-model="field.key" aria-label="字段键" placeholder="字段键" /><input v-model="field.label" aria-label="字段名称" placeholder="显示名称" /><select v-model="field.type" aria-label="字段类型"><option v-for="kind in types" :key="kind">{{kind}}</option></select><label><input v-model="field.required" type="checkbox" />必填</label><label><input v-model="field.multiple" type="checkbox" />多值</label><button class="v21-link text-button" @click="form.fields.splice(index,1)">删除</button></div><div class="v21-field"><label for="dataset-key">唯一键字段</label><select id="dataset-key" v-model="form.unique_key_fields[0]"><option value="">请选择</option><option v-for="field in form.fields.filter(f=>f.required&&!f.multiple&&f.type!=='json')" :key="field.key" :value="field.key">{{field.label||field.key}}</option></select></div><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="createDataset">创建数据集</el-button></template></el-dialog>
 </div>
</template>
<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue';
import { useRoute } from 'vue-router';
import { ElMessage } from 'element-plus';
import { api,errorText,jsonValue,type Dataset,type DatasetField,type RecordRow } from './api';
import { projectId } from './state';
const route=useRoute(); const all=ref<Dataset[]>([]),fields=ref<DatasetField[]>([]),records=ref<RecordRow[]>([]),selected=ref(0),page=ref(1),total=ref(0),query=ref(''),loading=ref(false),saving=ref(false),error=ref(''),dialog=ref(false),recordDrawer=ref(false),documentDialog=ref(false),detail=ref<any>(null),documentContent=ref('');
const types=['string','integer','number','boolean','datetime','url','json'];
const form=reactive({code:'',name:'',record_type:'',empty_value_policy:'preserve',unique_key_fields:[''],fields:[{key:'url',label:'URL',type:'url',required:true,multiple:false}]});
const datasets=computed(()=>all.value.filter(d=>d.project_id===projectId.value));const current=computed(()=>datasets.value.find(d=>d.id===selected.value));
const keyNames=computed(()=>{const keys=current.value?.unique_key_fields;const parsed=Array.isArray(keys)?keys:jsonValue(keys||'[]');return Array.isArray(parsed)?parsed as string[]:[];});
const filtered=computed(()=>records.value.filter(r=>!query.value||`${r.canonical_key} ${r.normalized}`.toLowerCase().includes(query.value.toLowerCase())));
function formatDate(value?:string){return value?new Date(value).toLocaleString():'—';}function display(value:any){return typeof value==='string'?value:JSON.stringify(value);}function summary(row:RecordRow){return Object.entries(jsonValue(row.normalized)).filter(([key])=>key!=='url'&&key!=='canonical_key').slice(0,3).map(([key,value])=>`${key}: ${display(value)}`).join(' · ')||'—';}
async function load(){loading.value=true;error.value='';try{all.value=await api.datasets();const fromRoute=Number(route.query.dataset)||0;if(datasets.value.some(d=>d.id===fromRoute))selected.value=fromRoute;else if(!datasets.value.some(d=>d.id===selected.value))selected.value=datasets.value[0]?.id||0;await choose(selected.value);}catch(e){error.value=errorText(e);}finally{loading.value=false;}}
async function choose(id:number){selected.value=id;page.value=1;query.value='';if(!id){fields.value=[];records.value=[];return;}const [schema]=await Promise.all([api.dataset(id),loadRecords()]);fields.value=schema.fields||[];}
async function loadRecords(){if(!selected.value)return;const response=await api.records(selected.value,page.value);records.value=response.list||[];total.value=response.total||0;}
async function openRecord(id:number){try{const result=await api.record(id);if(result.record?.dataset_id!==selected.value)throw new Error('记录不属于当前数据集');detail.value=result;recordDrawer.value=true;}catch(e){ElMessage.error(errorText(e));}}
async function showDocument(id:number){try{const response=await api.document(id);documentContent.value=response.document?.content||'';documentDialog.value=true;}catch(e){ElMessage.error(errorText(e));}}
function addField(){form.fields.push({key:'',label:'',type:'string',required:false,multiple:false});}
async function createDataset(){if(!form.name.trim()||!form.code.trim()||!form.record_type.trim()||!form.unique_key_fields[0]){ElMessage.warning('请填写名称、标识、类型和唯一键');return;}saving.value=true;try{const row=await api.createDataset({...form,project_id:projectId.value});dialog.value=false;await load();await choose(row.id);ElMessage.success('数据集已创建');}catch(e){ElMessage.error(errorText(e));}finally{saving.value=false;}}
watch(projectId,()=>{detail.value=null;recordDrawer.value=false;selected.value=0;load();});watch(()=>route.query.dataset,load);onMounted(load);
</script>
<style scoped>.dataset-item{width:100%;border:0;border-top:1px solid var(--v21-line);background:#fff;display:flex;align-items:center;justify-content:space-between;padding:14px 8px;text-align:left;cursor:pointer;color:var(--v21-ink)}.dataset-item.active,.dataset-item:hover{background:#eff3fb}.dataset-item strong,.dataset-item small{display:block}.dataset-item small{color:var(--v21-muted)}.records-head,.fields-title{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-bottom:15px}.records-head h2{margin:0}.pager{display:flex;justify-content:flex-end;align-items:center;gap:12px;padding-top:16px}.facts{display:grid;grid-template-columns:150px minmax(0,1fr);gap:0}.facts dt,.facts dd{padding:9px;margin:0;border-bottom:1px solid var(--v21-line);word-break:break-word}.facts dt{font-weight:700;color:var(--v21-muted)}.text-button{border:0;background:transparent;padding:0}.document-content{white-space:pre-wrap;word-break:break-all;max-height:65vh;overflow:auto;background:#f5f7fb;padding:16px}.form-pair{display:grid;grid-template-columns:1fr 1fr;gap:0 15px}.field-editor{display:grid;grid-template-columns:1fr 1fr 105px 65px 65px 45px;gap:6px;align-items:center;margin-bottom:7px}.field-editor input:not([type=checkbox]),.field-editor select{min-width:0;border:1px solid #cfd8e4;border-radius:7px;padding:8px}.field-editor label{font-size:12px;white-space:nowrap}@media(max-width:760px){.form-pair{grid-template-columns:1fr}.field-editor{grid-template-columns:1fr 1fr 100px}.field-editor>*{min-width:0}}</style>
