<template>
 <div class="v21-stack"><header class="v21-header"><div><div class="v21-eyebrow">Workspace / 运行</div><h1>运行记录</h1><p>从采集器看到页面任务、失败原因和原始文档。</p></div><el-button @click="load">刷新</el-button></header><p v-if="error" class="v21-error" role="alert">{{error}}</p>
  <div class="run-layout"><section class="v21-card"><h2>最近运行</h2><div v-if="!runs.length" class="v21-empty">当前项目还没有运行。发布采集器后可在工作台手动执行。</div><button v-for="run in runs" :key="run.id" class="run-item" :class="{active:selectedId===run.id}" @click="select(run.id)"><span><strong>{{workflowName(run.workflow_id)}}</strong><small>{{formatDate(run.created_at)}} · 版本 #{{run.workflow_version_id}}</small></span><span class="v21-status" :class="statusClass(run.status)">{{run.status}}</span></button><div class="pager"><el-button :disabled="page<=1" @click="page--;load()">上一页</el-button><span>{{page}} / {{Math.max(1,Math.ceil(total/20))}}</span><el-button :disabled="page*20>=total" @click="page++;load()">下一页</el-button></div></section>
   <section class="v21-card run-detail"><div v-if="!detail" class="v21-empty">选择一次运行查看页面任务和结果。</div><template v-else><div class="detail-head"><div><span class="v21-eyebrow">{{workflowName(detail.run.workflow_id)}} / v#{{detail.run.workflow_version_id}}</span><h2>运行 #{{detail.run.id}}</h2><span class="v21-status" :class="statusClass(detail.run.status)">{{detail.run.status}}</span></div><span class="v21-muted">{{formatDate(detail.run.created_at)}}</span></div><div class="v21-grid two run-metrics"><div class="v21-note">开始：{{formatDate(detail.run.started_at)}}</div><div class="v21-note">结束：{{formatDate(detail.run.finished_at)}}</div></div><h3>运行摘要</h3><pre class="json-box">{{pretty(detail.run.summary)}}</pre><h3>页面任务</h3><div v-if="!detail.tasks?.length" class="v21-empty">暂无页面任务。</div><button v-for="task in detail.tasks" :key="task.id" class="task-item" :class="{active:activeTask?.id===task.id}" @click="activeTask=task"><span><strong>{{task.step_name}} · 任务 #{{task.id}}</strong><small>{{task.error_message||taskURL(task)}}</small></span><span class="v21-status" :class="statusClass(task.status)">{{task.status}}</span></button></template></section>
   <aside class="v21-card inspect"><h2>任务检查</h2><div v-if="!activeTask" class="v21-empty">选择页面任务查看获取结果与错误。</div><template v-else><div class="v21-row"><strong>阶段</strong><span>{{activeTask.step_name}}</span></div><div class="v21-row"><strong>状态</strong><span>{{activeTask.status}}</span></div><div class="v21-row"><strong>页面</strong><span>{{taskURL(activeTask)}}</span></div><p v-if="activeTask.error_message" class="v21-error">{{activeTask.error_message}}</p><div class="v21-actions"><el-button :disabled="!activeTask.output_document_id" @click="loadDocument(activeTask.output_document_id!)">查看原文</el-button><router-link v-if="detail" class="v21-link" :to="{path:'/workspace/collectors',query:{id:String(detail.run.workflow_id)}}">打开采集器 →</router-link></div><div v-if="document"><h3>原文 #{{document.id}}</h3><p class="v21-muted">{{document.document_type}} · {{document.content_size}} bytes</p><pre class="document-box">{{document.content}}</pre></div></template></aside></div>
 </div>
</template>
<script setup lang="ts">
import { computed,onMounted,ref,watch } from 'vue';
import { useRoute,useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import { api,errorText,jsonValue,workflowPages,type Run,type Task,type Workflow } from './api';
import { projectId } from './state';
const route=useRoute(),router=useRouter();const allWorkflows=ref<Workflow[]>([]),allRuns=ref<Run[]>([]),detail=ref<{run:Run;tasks:Task[]}|null>(null),activeTask=ref<Task|null>(null),document=ref<any>(null),selectedId=ref(0),page=ref(1),total=ref(0),error=ref('');
const workflows=computed(()=>allWorkflows.value.filter(w=>w.project_id===projectId.value));const runs=computed(()=>allRuns.value.filter(r=>workflows.value.some(w=>w.id===r.workflow_id)));
function workflowName(id:number){return allWorkflows.value.find(w=>w.id===id)?.name||`采集器 #${id}`;}function formatDate(value?:string){return value?new Date(value).toLocaleString():'—';}function statusClass(value:string){return value==='succeeded'||value==='completed'?'ok':value==='failed'||value==='cancelled'?'bad':'warn';}function pretty(value:string){return JSON.stringify(jsonValue(value),null,2);}function taskURL(task:Task){return jsonValue(task.input).url||'使用采集器入口 URL';}
async function load(){error.value='';detail.value=null;activeTask.value=null;document.value=null;try{const [w,r]=await Promise.all([projectId.value?workflowPages(projectId.value):Promise.resolve([]),projectId.value?api.runs(page.value,projectId.value):Promise.resolve({list:[],total:0})]);allWorkflows.value=w||[];allRuns.value=r.list||[];total.value=r.total||0;const id=Number(route.query.id)||runs.value[0]?.id;if(id)await select(id);else selectedId.value=0;}catch(e){error.value=errorText(e);}}
async function select(id:number){document.value=null;try{const result=await api.runDetail(id);if(!workflows.value.some(item=>item.id===result.run.workflow_id))throw new Error('运行不属于当前项目');selectedId.value=id;detail.value=result;activeTask.value=result.tasks?.[0]||null;if(Number(route.query.id)!==id)router.replace({path:'/workspace/runs',query:{id:String(id)}});}catch(e){detail.value=null;activeTask.value=null;selectedId.value=0;ElMessage.error(errorText(e));}}
async function loadDocument(id:number){try{document.value=(await api.document(id)).document;}catch(e){ElMessage.error(errorText(e));}}
watch(projectId,async()=>{page.value=1;selectedId.value=0;await router.replace({path:'/workspace/runs'});await load();});watch(()=>route.query.id,id=>{if(Number(id)&&Number(id)!==selectedId.value)load();});onMounted(load);
</script>
<style scoped>.run-layout{display:grid;grid-template-columns:280px minmax(0,1fr) 270px;gap:16px;align-items:start}.run-item,.task-item{width:100%;display:flex;justify-content:space-between;align-items:center;gap:10px;text-align:left;padding:13px 7px;border:0;border-top:1px solid var(--v21-line);background:#fff;color:var(--v21-ink);cursor:pointer}.run-item.active,.run-item:hover,.task-item.active,.task-item:hover{background:#eff3fb}.run-item strong,.run-item small,.task-item strong,.task-item small{display:block}.run-item small,.task-item small{font-size:11px;color:var(--v21-muted);word-break:break-all}.pager{display:flex;align-items:center;justify-content:center;gap:8px;margin-top:15px}.detail-head{display:flex;align-items:start;justify-content:space-between;gap:12px}.detail-head h2{font-size:23px;margin:5px 0}.run-metrics{margin:17px 0}.run-detail h3,.inspect h3{margin:20px 0 8px}.json-box,.document-box{background:#f6f8fb;border:1px solid var(--v21-line);padding:11px;border-radius:8px;white-space:pre-wrap;word-break:break-word;max-height:370px;overflow:auto;font:12px/1.5 Consolas,monospace}.inspect .v21-row{word-break:break-word}.inspect .v21-actions{align-items:center;margin-top:16px}@media(max-width:1250px){.run-layout{grid-template-columns:240px minmax(0,1fr)}.inspect{grid-column:2}}@media(max-width:760px){.run-layout{grid-template-columns:1fr}.inspect{grid-column:auto}}</style>
