[project]
name = "crawler-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "drissionpage>=4.1.1.2",
]

[[tool.uv.index]]
name = "tsinghua"
url = "https://mirrors.aliyun.com/pypi/simple"
default = true
